
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init and Apply
      run: |
        cd aws
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

    - name: Deploy AI Model to SageMaker
      run: |
        pip install boto3
        python deploy_model_sagemaker.py
